# Build configuration
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
          any_map: true
      retrofit_generator:
        enabled: true
