name: seed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.7.3
  dio: ^5.9.0
  json_annotation: ^4.9.0

  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  go_router: ^16.2.2
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  logger: ^2.5.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto\Roboto-Bold.ttf
        - asset: assets/fonts/roboto\Roboto-Medium.ttf
        - asset: assets/fonts/roboto\Roboto-Regular.ttf
        - asset: assets/fonts/roboto\Roboto-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
